apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  selector:
    app: movie
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
