apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-movie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-movie
  serviceName: postgres-movie
  template:
    metadata:
      labels:
        app: postgres-movie
    spec:
      containers:
      - name: postgres-movie
        image: postgres:12.0-alpine
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rootpass-movie
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: rootpass-movie
                key: user
          - name: POSTGRES_DB
            value: movie_db_dev
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-data-movie
      volumes:
        - name: postgres-data-movie
          persistentVolumeClaim:
            claimName: postgres-data-movie
